project_id = "dtfzuoijnbvrgwjoxcfq"

[api]
enabled = true
port = 54321

[functions]
enabled = true
port = 54322

[functions.send-email]
verify_jwt = true

[functions.create-expense-payment]
verify_jwt = true

[functions.verify-expense-payment]
verify_jwt = true