steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'appengine.yaml']
timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY