steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci']
    
  # Build the application
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    
  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']

timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY