apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: travel-app

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- nginx-config.yaml
- deployment.yaml
- frontend-deployment.yaml
- ingress.yaml
- hpa.yaml
- network-policy.yaml
- loadgenerator.yaml

images:
- name: wandertogether-backend
  newName: gcr.io/keen-opus-470223-b7/wandertogether-backend
  newTag: latest
- name: wandertogether-frontend
  newName: gcr.io/keen-opus-470223-b7/wandertogether-frontend
  newTag: latest
- name: wandertogether-loadgenerator
  newName: gcr.io/keen-opus-470223-b7/wandertogether-loadgenerator
  newTag: latest

replicas:
- name: wandertogether-backend
  count: 1
- name: wandertogether-frontend
  count: 1

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: wandertogether-backend
    namespace: travel-app
  spec:
    template:
      metadata:
        labels:
          version: v1
          
commonLabels:
  app.kubernetes.io/name: wandertogether
  app.kubernetes.io/instance: wandertogether-prod
  app.kubernetes.io/version: v1.0.0
  app.kubernetes.io/component: travel-app
  app.kubernetes.io/part-of: wandertogether-platform
  app.kubernetes.io/managed-by: kustomize